# Edit this file as needed. To cancel alerting on a field,
# comment out or delete its threshold entry.

alert_thresholds:
    num_err_log_entries: 0
    unsafe_shutdowns: 20
    percentage_used: 50
    media_errors: 0
    health_score: 90
    mean_temperature: 70 #Average of all sensor readings, in Celsius

alert_settings:
    alerts_enabled: true
    # See https://pypi.org/project/pytimeparse/ for possible values
    # (This regex is probably all you need: \d+\s*[wdhm])
    # Do not repeat alerts previously sent untio this interval passes
    alert_interval: 1w
    # maximum number of emails that can be sent per hour (default 20)
    rate_limit: 20
    # Send a "healthy" notification when alert interval is reached and there are no alerts
    notify_when_healthy: true
    # Send an email alert if no new collection log record is found in the specified time period
    # Specify the time period in accordance wtih pytimeparse
    # Delete the entry or leave the value empty to omit this check
    notify_no_data_after: 4h

LOG_FILE_NAME: /var/log/nvme_mon/nvme_health.json