"""
***** Generated by ChatGPT *****

Path helpers for nvme_mon.

Handles:
- bundled (read-only) resources
- writable runtime data
- frozen (PyInstaller) and non-frozen execution
"""

from pathlib import Path
import os
import sys


def is_frozen() -> bool:
    """Return True if running from a PyInstaller bundle."""
    return hasattr(sys, "_MEIPASS")


def resource_dir() -> Path:
    """
    Directory containing bundled, read-only resources.
    """
    if is_frozen():
        return Path(sys._MEIPASS)
    return Path(__file__).parent


def resource_path(name: str) -> Path:
    """
    Path to a bundled resource file (read-only).
    """
    return resource_dir() / name


def app_data_dir(app_name: str = "nvme_mon") -> Path:
    """
    Writable per-user application data directory.
    """
    if os.name == "nt":
        base = Path(os.environ.get("APPDATA", Path.home()))
        path = base / app_name
    else:
        path = Path.home() / f".{app_name}"

    path.mkdir(parents=True, exist_ok=True)
    return path


def app_data_path(name: str, app_name: str = "nvme_mon") -> Path:
    """
    Path to a writable runtime file.
    """
    return app_data_dir(app_name) / name
