"""
***** Generated by ChatGPT *****

Path helpers for nvme_mon.

Handles:
- bundled (read-only) resources
- writable runtime data
- frozen (PyInstaller) and non-frozen execution
"""

from pathlib import Path
import os
import sys


def is_frozen() -> bool:
    """Return True if running from a PyInstaller bundle."""
    return hasattr(sys, "_MEIPASS")


def resource_dir() -> Path:
    """
    Directory containing bundled, read-only resources.
    """
    if getattr(sys, "frozen", False):
        return Path(sys.executable).resolve().parent
    return Path(__file__).resolve().parent

def resource_path(name: str) -> Path:
    """
    Path to a bundled resource file (read-only).
    """
    return resource_dir() / name


def app_data_dir(app_name: str = "nvme_mon") -> Path:
    """
    Writable per-user application data directory.
    """
    if is_frozen():
        return Path(os.environ.get("NVME_MON_STATE_DIR", "/var/lib/nvme_mon"))
    return Path(__file__).resolve().parent


def app_data_path(name: str, app_name: str = "nvme_mon") -> Path:
    """
    Path to a writable runtime file.
    """
    return app_data_dir(app_name) / name
